#端口设置
server:
  port: 8080

#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myweb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: lzh1234
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

#日志级别（一般设置为INFO）
logging:
  level:
    cn:
      edu:
        guet:
          mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.guet.bean


